/**
 * The checkpoint-gallery manifest (Slice 7): one training run, several
 * checkpoints, each evaluated on several tracks, each pointing at a
 * trajectory file served from the app's own origin.
 *
 * Generated by `uv run python -m apex_trainer.debug.export_gallery`; validated
 * here (Zod is the source of truth, `gallery.schema.json` is generated from it
 * and checked in CI, and the Python exporter's tests validate against that).
 */
import { z } from 'zod';

export const GALLERY_SCHEMA_VERSION = 1;

/** A bare filename inside the gallery directory — never a path, scheme or host. */
const bareFilename = z.string().regex(/^[a-z0-9_.-]+\.json$/);

export const galleryEntrySchema = z.object({
  trackId: z.string().regex(/^[a-z0-9_]+$/),
  file: bareFilename,
  crashed: z.boolean(),
  laps: z.number().int().nonnegative(),
  bestLapSec: z.number().positive().nullable(),
  lapTimesSec: z.array(z.number().positive()),
  distanceM: z.number().nonnegative(),
  /** Sample rate of the trajectory file, Hz (60 = sim rate, 30 = decimated). */
  sampleHz: z.number().positive(),
});

export const galleryCheckpointSchema = z.object({
  step: z.number().int().nonnegative(),
  /** Short human label, e.g. "8M · generalist". */
  label: z.string().min(1),
  /** One sentence for the UI; may be empty. */
  note: z.string(),
  entries: z.array(galleryEntrySchema).min(1),
});

export const galleryManifestSchema = z
  .object({
    schemaVersion: z.literal(GALLERY_SCHEMA_VERSION),
    runId: z.string().min(1),
    title: z.string().min(1),
    description: z.string(),
    physicsConfigHash: z.string().regex(/^[0-9a-f]{12}$/),
    /** The run's PPO/train config summary for the UI (free-form, small). */
    config: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
    tracks: z.array(z.string().regex(/^[a-z0-9_]+$/)).min(1),
    checkpoints: z.array(galleryCheckpointSchema).min(1),
    createdAt: z.string().min(1),
  })
  .refine((m) => m.checkpoints.every((c) => c.entries.every((e) => m.tracks.includes(e.trackId))), {
    message: 'every entry.trackId must be listed in tracks',
  })
  .refine((m) => new Set(m.checkpoints.map((c) => c.step)).size === m.checkpoints.length, {
    message: 'checkpoint steps must be unique',
  });

export type GalleryManifest = z.infer<typeof galleryManifestSchema>;
export type GalleryCheckpoint = z.infer<typeof galleryCheckpointSchema>;
export type GalleryEntry = z.infer<typeof galleryEntrySchema>;

export type GalleryParseResult =
  { ok: true; manifest: GalleryManifest } | { ok: false; error: string };

export function parseGalleryManifest(raw: unknown): GalleryParseResult {
  const version =
    typeof raw === 'object' && raw !== null
      ? (raw as { schemaVersion?: unknown }).schemaVersion
      : undefined;
  if (version !== GALLERY_SCHEMA_VERSION) {
    return {
      ok: false,
      error: `unsupported gallery schemaVersion ${JSON.stringify(version)}; expected ${GALLERY_SCHEMA_VERSION}`,
    };
  }
  const r = galleryManifestSchema.safeParse(raw);
  if (r.success) return { ok: true, manifest: r.data };
  const issues = r.error.issues
    .slice(0, 5)
    .map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`)
    .join('; ');
  return { ok: false, error: `invalid gallery manifest: ${issues}` };
}

export function galleryJsonSchema(): Record<string, unknown> {
  return z.toJSONSchema(galleryManifestSchema, { target: 'draft-2020-12', io: 'input' });
}

/** Entry for a checkpoint on a track, if evaluated there. */
export function findEntry(cp: GalleryCheckpoint, trackId: string): GalleryEntry | undefined {
  return cp.entries.find((e) => e.trackId === trackId);
}
